name: Release APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: List Build Artifacts
        run: ls -R app/build/outputs/apk/debug/

      - name: Zip APK
        run: |
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            zip -r TorchVista.zip app/build/outputs/apk/debug/app-debug.apk
          else
            echo "APK file not found!" >&2
            exit 1
          fi

      - name: Verify ZIP file creation
        run: |
          if [ -f TorchVista.zip ]; then
            echo "ZIP file found: TorchVista.zip"
          else
            echo "ZIP file not found!"
            exit 1
          fi

      - name: Upload ZIP to Release
        uses: ncipollo/release-action@v1.9.0 # Updated action version
        with:
          artifacts: TorchVista.zip
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          releaseName: "Release ${{ github.event.release.tag_name }}"
          body: "Automated release of TorchVista APK"
          draft: false
          prerelease: false
          replacesArtifacts: true  # Ensure artifacts are replaced if they already exist

      - name: Notify Failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: 'Build failed! Check the details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
