name: Release APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Update to Java 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: List Build Artifacts
        run: ls -R app/build/outputs/apk/release/

      - name: Zip APK
        run: |
          if [ -f app/build/outputs/apk/release/app-release.apk ]; then
            zip -r TorchVista.zip app/build/outputs/apk/release/app-release.apk
          else
            echo "APK file not found!" >&2
            exit 1
          fi

      - name: Upload ZIP to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: TorchVista.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Notify on failure (example with Slack)
      - name: Notify Failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: 'Build failed! Check the details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
