name: Release APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: List Build Artifacts
        run: ls -R app/build/outputs/apk/debug/

      - name: Zip APK
        run: |
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            zip -r TorchVista.zip app/build/outputs/apk/debug/app-debug.apk
          else
            echo "APK file not found!" >&2
            exit 1
          fi

      - name: Check for Existing Release
        id: check-release
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "Checking if release with tag ${TAG_NAME} exists..."
          RELEASE_EXISTS=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${TAG_NAME}" | jq '.message == "Not Found"')
          echo "::set-output name=exists::$RELEASE_EXISTS"

      - name: Upload ZIP to Release
        if: steps.check-release.outputs.exists == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: TorchVista.zip
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ github.event.release.tag_name }}

      - name: Notify Failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: 'Build failed! Check the details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
